version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:latest
        container_name: ${NGINX_CONTAINER:-nginx}
        ports:
            - "50080:80"
            - "50443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/cert:/etc/cert
            - ./nginx/log:/var/log/nginx
        environment:
            TZ: ${TZ:-Asia/Shanghai}
        depends_on:
            - php
            - mysql
        privileged: true
        networks:
            - lemp
    mysql:
        image: mariadb:latest
        container_name: ${MYSQL_CONTAINER:-mysql}
        ports:
            - "53306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Shanghai}
        networks:
            - lemp
    php:
        build:
            context: ./php/.
            dockerfile: Dockerfile
        container_name: ${PHP_CONTAINER:-php}
        volumes:
            - ./src:/var/www/html
        ports:
            - "59000:9000"
        networks:
            - lemp
    redis:
        image: redis:latest
        container_name: ${REDIS_CONTAINER:-redis}
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - "56379:6379"
        networks:
            - lemp
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: ${PMA_CONTAINER:-phpmyadmin}
        ports:
            - "58080:80"
        environment:
            PMA_HOST: ${PMA_HOST:-mysql}
        networks:
          - lemp
