version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:latest
        container_name: zknginx
        ports:
            - "50080:80"
            - "50443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/cert:/etc/cert
            - ./nginx/log:/var/log/nginx
        depends_on:
            - php
            - mysql
        privileged: true
        networks:
            - lemp
    mysql:
        image: mariadb:latest
        container_name: zkmysql
        ports:
            - "53306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Shanghai"
        networks:
            - lemp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: zkphp
        volumes:
            - ./src:/var/www/html
        ports:
            - "59000:9000"
        networks:
            - lemp
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: zkphpmyadmin
        ports:
            - "58080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
          - lemp