version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:latest
        container_name: zknginx
        ports:
            - "50080:80"
            - "50443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/log:/var/log/nginx
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/data:/etc/nginx/cert/data
        depends_on:
            - php
            - mysql
        privileged: true
        networks:
            - lemp
    mysql:
        image: mariadb:latest
        container_name: zkmysql
        ports:
            - "53306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Shanghai"
        networks:
            - lemp
    php:
        build:
            context: ./php/.
            dockerfile: Dockerfile
        container_name: zkphp
        volumes:
            - ./src:/var/www/html
        ports:
            - "59000:9000"
        networks:
            - lemp
    redis:
        image: redis:latest
        container_name: zkredis
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - "56379:6379"
        networks:
            - lemp
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: zkphpmyadmin
        ports:
            - "58080:80"
        environment:
            PMA_HOST: zkmysql
        networks:
          - lemp
    certbot:
        image: certbot:latest
        command: certonly --webroot --webroot-path=/etc/nginx/cert/data --email your-email@domain.com --agree-tos --no-eff-email -d sub.domain.com
        volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/data:/etc/nginx/cert/data
          - ./certbot/lib:/var/lib/letsencrypt
          - ./certbot/log:/var/log/letsencrypt
        networks:
          - lemp
