version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:latest
        container_name: ${NGINX_CONTAINER:-nginx}
        ports:
            - "50080:80"
            - "50443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/cert:/etc/cert
            - ./nginx/log:/var/log/nginx
        environment:
            TZ: ${TZ:-Asia/Shanghai}
        depends_on:
            - php5
            - php7
            - mysql
        privileged: true
        networks:
                lemp:
                  aliases:
                   - domain1.com
                   - domain2.com
    mysql:
        image: mariadb:latest
        container_name: ${MYSQL_CONTAINER:-mysql}
        ports:
            - "53306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Shanghai}
        networks:
            - lemp
    mongo:
        image: mongo:latest
        container_name: ${MONGO_CONTAINER:-mongo}
        ports:
            - "57017:27017"
        volumes:
            - ./mongo:/var/lib/mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - lemp
    php7:
        build:
            context: ./php7/.
            dockerfile: Dockerfile
        container_name: ${PHP7_CONTAINER:-php7}
        volumes:
            - ./src:/var/www/html
        ports:
            - "59000:9000"
        networks:
            - lemp
    php5:
        build:
            context: ./php5/.
            dockerfile: Dockerfile
        container_name: ${PHP5_CONTAINER:-php5}
        volumes:
            - ./src:/var/www/html
        ports:
            - "59001:9000"
        networks:
            - lemp
    redis:
        image: redis:latest
        container_name: ${REDIS_CONTAINER:-redis}
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - "56379:6379"
        networks:
            - lemp
    pma1:
        build:
            context: ./phpmyadmin/.
            dockerfile: Dockerfile
        container_name: pma-dev
        ports:
            - "58080:80"
        environment:
            PMA_HOST: ${PMA_HOST:-mysql}
            PMA_ARBITRARY: 1
        networks:
          - lemp
    pma2:
        build:
            context: ./phpmyadmin/.
            dockerfile: Dockerfile
        container_name: pma-ro
        ports:
            - "58081:80"
        environment:
            PMA_HOST: ${PMA_HOST:-mysql}
            PMA_ARBITRARY: 1
            PMA_PORT: 3307
        networks:
          - lemp
